{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "463f8e64-9605-451d-a8fb-a925c3e9dc31",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "from status_tracker import initialize_feature_status\n",
    "\n",
    "def read_client_requirements(filename=\"Client Requirement.txt\"):\n",
    "    with open(filename, 'r') as file:\n",
    "        lines = [line.strip() for line in file.readlines() if line.strip()]\n",
    "    return lines\n",
    "\n",
    "def parse_requirements(lines):\n",
    "    data = {\n",
    "        \"Project\":None,\n",
    "        \"Timeline\":None,\n",
    "        \"Priority\":None,\n",
    "        \"Features\":[]\n",
    "    }\n",
    "    current_key=\"\"\n",
    "    for line in lines:\n",
    "        if line.startswith(\"Project:\"):\n",
    "            data[\"Project\"] =line.split(\":\", 1)[1].strip()\n",
    "        elif line.startswith(\"Timeline:\"):\n",
    "            data[\"Timeline\"]= line.split(\":\", 1)[1].strip()\n",
    "        elif line.startswith(\"Priority:\"):\n",
    "            data[\"Priority\"] =line.split(\":\", 1)[1].strip()\n",
    "        elif line.startswith(\"Features:\"):\n",
    "            current_key=\"Features\"\n",
    "        elif line.startswith(\"-\") and current_key == \"Features\":\n",
    "            data[\"Features\"].append(line.lstrip(\"- \").strip())\n",
    "    return data\n",
    "\n",
    "def print_summary(data):\n",
    "    print(\"\\nProject Summary Report\")\n",
    "    print(\"-\"*25)\n",
    "    print(f\"Project: {data['Project']}\")\n",
    "    print(f\"Timeline: {data['Timeline']}\")\n",
    "    print(f\"Priority: {data['Priority']}\")\n",
    "    print(\"Features to Implement:\")\n",
    "    for feature in data['Features']:\n",
    "        print(f\" - {feature}\")\n",
    "\n",
    "def write_summary_to_file(data, filename=\"project_summary.txt\"):\n",
    "    with open(filename, \"w\", encoding=\"utf-8\") as file:\n",
    "        file.write(\"Project Summary Report\\n\")\n",
    "        file.write(\"-\"*25+\"\\n\")\n",
    "        file.write(f\"Project: {data['Project']}\\n\")\n",
    "        file.write(f\"Timeline: {data['Timeline']}\\n\")\n",
    "        file.write(f\"Priority: {data['Priority']}\\n\")\n",
    "        file.write(\"Features to Implement:\\n\")\n",
    "        for feature in data['Features']:\n",
    "            file.write(f\" - {feature}\\n\")\n",
    "\n",
    "def export_to_json(data, filename=\"project_summary.json\"):\n",
    "    data[\"Features\"]= initialize_feature_status(data[\"Features\"])\n",
    "    with open(filename, \"w\", encoding=\"utf-8\") as json_file:\n",
    "        json.dump(data, json_file, indent=4)\n",
    "\n",
    "if __name__ ==\"__main__\":\n",
    "    lines=read_client_requirements()\n",
    "    parsed_data=parse_requirements(lines)\n",
    "    print_summary(parsed_data)\n",
    "    write_summary_to_file(parsed_data)\n",
    "    export_to_json(parsed_data)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
